INV_FILE="setme"

OM1_HOSTNAME="setme"
OM2_HOSTNAME="setme"
OM3_HOSTNAME="setme"
SCM1_HOSTNAME="setme"
SCM2_HOSTNAME="setme"
SCM3_HOSTNAME="setme"
DN1_HOSTNAME="setme"
DN2_HOSTNAME="setme"
DN3_HOSTNAME="setme"
RECON_HOSTNAME="setme"
S3G1_HOSTNAME="setme"
S3G2_HOSTNAME="setme"
S3G3_HOSTNAME="setme"

FREEIPA_HOSTNAME="setme"

HOSTNAME_SUFFIX="setme"
